avi_credentials:
  controller: "{{controller_ip}}"
  username: admin
  password: "{{password}}"
  api_version: 18.1.5

ew_subnet: "10.0.0.0"
ew_subnet_start: "10.0.0.8"
ew_subnet_end: "10.0.0.254"

ns_subnet: "10.0.1.0"
ns_subnet_start: "10.0.1.2"
ns_subnet_end: "10.0.1.255"

project_name: "avistio-gtm"
#kube_master_node: "10.70.119.34:8443"
kube_master_node: "35.226.173.104:6443"
