# TODO: parameterize the controller version and declare it in a central configuration
- hosts: controllers
  roles:
  - role: avinetworks.avicontroller
    become: true
    ansible_memtotal_mb: 13000
    con_version: 18.2.1-9010-20181220.082642 
    con_cores: 4
    con_disk_gb: 32
    con_max_cores: 8
    con_memory_gb: 12
