- hosts: controllers
  roles:
  - role: avinetworks.avicontroller
    become: true
    ansible_memtotal_mb: 13000
    con_version: 18.1.5-9249-20181212.055920
    con_cores: 4
    con_disk_gb: 32
    con_max_cores: 8
    con_memory_gb: 12
